language: node_js
node_js: 12
script: npm run build-release

deploy:
  provider: pages:git
  local_dir: docs/
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
  edge: true
