name: Create Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install node modules and verify build
        run: npm ci && npm run build-release

      - name: Publish
        if: github.repository == 'morganstanley/ts-mocking-bird'
        uses: JS-DevTools/npm-publish@v2
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Print release output
        if: ${{ steps.publish.outputs.type }}
        run: echo Release ID ${{ steps.publish.outputs.id }}


      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ steps.publish.outputs.type }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ steps.publish.outputs.tag }}"
