name: Compatible Typescript Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        typescript-version: [5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6 ]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Use Node.js 22.x
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22.x
    - run: npm ci
    - run: npm run build
    - run: npm install typescript@${{ matrix.typescript-version }} 
    - run: npm run compatibility-test
